---
- name: block in firewall
  iptables:
    chain: INPUT
    destination_port: "{{ smartit_port }}"
    protocol: tcp
    jump: DROP
  become: yes

- name: stop smartit
  shell: "{{ smartit_bin }} stop"

- name: start smartit
  shell: "{{ smartit_bin }} start"

- name: wait for smartit to come up
  wait_for:
    port: "{{ smartit_port }}"
    delay: 30

- name: allow in firewall
  iptables:
    chain: INPUT
    destination_port: "{{ smartit_port }}"
    protocol: tcp
    jump: ACCEPT
  become: yes